name: AGMllc
favicon: null
layout_spectrum: 0.8530466
typography_spectrum: 0.6523297
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'American Group Management, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0E0E0E'
    - '#4D4A41'
    - '#A49B87'
    - '#A32830'
    - '#A36642'
  brandStrength: 0.8494624
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
