layout_spectrum: 0.8136201
color:
  saturation: 1
  brandStrength: 0.8584229
  lightness: 1
  brandColors:
    - '#0D0E13'
    - '#89877F'
    - '#925339'
    - '#C6B5A2'
    - '#393227'
  rhythmicContrast: 1
typography_spectrum: 0.6523297
name: AGMllc
